version: "3.7"

services:
  raidhelper:
    image: znibb/raidhelper:latest
    container_name: raidhelper
    env_file:
      - .env
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    networks:
      - raidhelper
    restart: unless-stopped
    volumes:
      - ./google_key.json:/raidhelper/google_key.json
      - ./config.json:/raidhelper/config.json

networks:
  raidhelper:
    name: raidhelper
