version: "3.7"

services:
  pricebot:
    image: znibb/raidhelper:latest
    container_name: raidhelper
    env_file:
      - .env
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    networks:
      - raidhelper
    restart: unless-stopped
    volume:
      - ./google_key.json:/raidhelper/google_key.json

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower_raidhelper
    environment:
      - "WATCHTOWER_LABEL_ENABLE=true"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - raidhelper
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 900

networks:
  pricebot:
    name: raidhelper
    driver: bridge
